// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CompetitionProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat.Protocol {

  /// <summary>Holder for reflection information generated from CompetitionProtocol.proto</summary>
  public static partial class CompetitionProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for CompetitionProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CompetitionProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDb21wZXRpdGlvblByb3RvY29sLnByb3RvEg1jaGF0LnByb3RvY29sIk8K",
            "BFVzZXISEQoJZmlyc3RuYW1lGAEgASgJEhAKCGxhc3RuYW1lGAIgASgJEhAK",
            "CHVzZXJuYW1lGAMgASgJEhAKCHBhc3N3b3JkGAQgASgJIkoKC1BhcnRpY2lw",
            "YW50EhAKCHVzZXJuYW1lGAEgASgJEgwKBG5hbWUYAiABKAkSCwoDYWdlGAMg",
            "ASgJEg4KBnRlc3RJZBgEIAEoCSIWCgRUZXN0Eg4KBnRlc3RJZBgBIAEoCSJb",
            "CgdUZXN0RFRPEhAKCHRlc3RUeXBlGAEgASgJEhcKD3Rlc3RBZ2VDYXRlZ29y",
            "eRgCIAEoCRIVCg1ub0NvbXBldGl0b3JzGAMgASgJEg4KBnRlc3RJZBgEIAEo",
            "CSJAChdUZXN0UGFydGljaXBhbnRSZWxhdGlvbhIOCgZ0ZXN0SWQYASABKAkS",
            "FQoNcGFydGljaXBhbnRJZBgCIAEoCSKrBAoSQ29tcGV0aXRpb25SZXF1ZXN0",
            "EjQKBHR5cGUYASABKA4yJi5jaGF0LnByb3RvY29sLkNvbXBldGl0aW9uUmVx",
            "dWVzdC5UeXBlEg8KBWVtcHR5GAIgASgJSAASIwoEdXNlchgDIAEoCzITLmNo",
            "YXQucHJvdG9jb2wuVXNlckgAEjEKC3BhcnRpY2lwYW50GAQgASgLMhouY2hh",
            "dC5wcm90b2NvbC5QYXJ0aWNpcGFudEgAEikKB3Rlc3REVE8YBSABKAsyFi5j",
            "aGF0LnByb3RvY29sLlRlc3REVE9IABJJChd0ZXN0UGFydGljaXBhbnRSZWxh",
            "dGlvbhgGIAEoCzImLmNoYXQucHJvdG9jb2wuVGVzdFBhcnRpY2lwYW50UmVs",
            "YXRpb25IABIjCgR0ZXN0GAcgASgLMhMuY2hhdC5wcm90b2NvbC5UZXN0SAAi",
            "zwEKBFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvZ2luEAESCgoGTG9nb3V0EAIS",
            "EgoOR2V0TG9nZ2VkVXNlcnMQAxIWChJGaW5kVXNlckJ5VXNlcm5hbWUQBBIT",
            "Cg9TYXZlUGFydGljaXBhbnQQBRISCg5GaW5kQWxsVGVzdER0bxAGEhAKDFNh",
            "dmVSZWxhdGlvbhAHEh0KGUZpbmRQYXJ0aWNpcGFudEJ5VXNlcm5hbWUQCBId",
            "ChlGaW5BbGxQYXJ0aWNpcGFudHNGb3JUZXN0EAlCCQoHcGF5bG9hZCKfBAoT",
            "Q29tcGV0aXRpb25SZXNwb25zZRI1CgR0eXBlGAEgASgOMicuY2hhdC5wcm90",
            "b2NvbC5Db21wZXRpdGlvblJlc3BvbnNlLlR5cGUSDQoFZW1wdHkYAiABKAkS",
            "DQoFZXJyb3IYAyABKAkSIgoFdXNlcnMYBCADKAsyEy5jaGF0LnByb3RvY29s",
            "LlVzZXISIQoEdXNlchgFIAEoCzITLmNoYXQucHJvdG9jb2wuVXNlchIoCgh0",
            "ZXN0RFRPcxgGIAMoCzIWLmNoYXQucHJvdG9jb2wuVGVzdERUTxIwCgxwYXJ0",
            "aWNpcGFudHMYByADKAsyGi5jaGF0LnByb3RvY29sLlBhcnRpY2lwYW50Ei8K",
            "C3BhcnRpY2lwYW50GAggASgLMhouY2hhdC5wcm90b2NvbC5QYXJ0aWNpcGFu",
            "dCLeAQoEVHlwZRILCgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEhIK",
            "Dk5ld1BhcnRpY2lwYW50EAMSEAoMVXNlckxvZ2dlZEluEAQSEQoNVXNlckxv",
            "Z2dlZE91dBAFEhIKDkdldExvZ2dlZFVzZXJzEAYSFgoSRmluZFVzZXJCeVVz",
            "ZXJuYW1lEAcSEgoORmluZEFsbFRlc3REdG8QCBIdChlGaW5kUGFydGljaXBh",
            "bnRCeVVzZXJuYW1lEAkSHgoaRmluZEFsbFBhcnRpY2lwYW50c0ZvclRlc3QQ",
            "CkI9CiVjb21wZXRpdGlvbi5uZXR3b3JrLnByb3RvYnVmZnByb3RvY29sQhRD",
            "b21wZXRpdGlvblByb3RvYnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.User), global::Chat.Protocol.User.Parser, new[]{ "Firstname", "Lastname", "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.Participant), global::Chat.Protocol.Participant.Parser, new[]{ "Username", "Name", "Age", "TestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.Test), global::Chat.Protocol.Test.Parser, new[]{ "TestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.TestDTO), global::Chat.Protocol.TestDTO.Parser, new[]{ "TestType", "TestAgeCategory", "NoCompetitors", "TestId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.TestParticipantRelation), global::Chat.Protocol.TestParticipantRelation.Parser, new[]{ "TestId", "ParticipantId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.CompetitionRequest), global::Chat.Protocol.CompetitionRequest.Parser, new[]{ "Type", "Empty", "User", "Participant", "TestDTO", "TestParticipantRelation", "Test" }, new[]{ "Payload" }, new[]{ typeof(global::Chat.Protocol.CompetitionRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.Protocol.CompetitionResponse), global::Chat.Protocol.CompetitionResponse.Parser, new[]{ "Type", "Empty", "Error", "Users", "User", "TestDTOs", "Participants", "Participant" }, null, new[]{ typeof(global::Chat.Protocol.CompetitionResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class User : pb::IMessage<User>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<User> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User(User other) : this() {
      firstname_ = other.firstname_;
      lastname_ = other.lastname_;
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public User Clone() {
      return new User(this);
    }

    /// <summary>Field number for the "firstname" field.</summary>
    public const int FirstnameFieldNumber = 1;
    private string firstname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Firstname {
      get { return firstname_; }
      set {
        firstname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastname" field.</summary>
    public const int LastnameFieldNumber = 2;
    private string lastname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Lastname {
      get { return lastname_; }
      set {
        lastname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 4;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as User);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(User other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Firstname != other.Firstname) return false;
      if (Lastname != other.Lastname) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Firstname.Length != 0) hash ^= Firstname.GetHashCode();
      if (Lastname.Length != 0) hash ^= Lastname.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Firstname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Firstname);
      }
      if (Lastname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Lastname);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Firstname.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Firstname);
      }
      if (Lastname.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Lastname);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Firstname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Firstname);
      }
      if (Lastname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Lastname);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(User other) {
      if (other == null) {
        return;
      }
      if (other.Firstname.Length != 0) {
        Firstname = other.Firstname;
      }
      if (other.Lastname.Length != 0) {
        Lastname = other.Lastname;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Firstname = input.ReadString();
            break;
          }
          case 18: {
            Lastname = input.ReadString();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Firstname = input.ReadString();
            break;
          }
          case 18: {
            Lastname = input.ReadString();
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant(Participant other) : this() {
      username_ = other.username_;
      name_ = other.name_;
      age_ = other.age_;
      testId_ = other.testId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private string age_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Age {
      get { return age_; }
      set {
        age_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testId" field.</summary>
    public const int TestIdFieldNumber = 4;
    private string testId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestId {
      get { return testId_; }
      set {
        testId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      if (TestId != other.TestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age.Length != 0) hash ^= Age.GetHashCode();
      if (TestId.Length != 0) hash ^= TestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Age);
      }
      if (TestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Age);
      }
      if (TestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Age);
      }
      if (TestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age.Length != 0) {
        Age = other.Age;
      }
      if (other.TestId.Length != 0) {
        TestId = other.TestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Age = input.ReadString();
            break;
          }
          case 34: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Age = input.ReadString();
            break;
          }
          case 34: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Test : pb::IMessage<Test>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Test> _parser = new pb::MessageParser<Test>(() => new Test());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Test> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test(Test other) : this() {
      testId_ = other.testId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test Clone() {
      return new Test(this);
    }

    /// <summary>Field number for the "testId" field.</summary>
    public const int TestIdFieldNumber = 1;
    private string testId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestId {
      get { return testId_; }
      set {
        testId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Test);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Test other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TestId != other.TestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TestId.Length != 0) hash ^= TestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Test other) {
      if (other == null) {
        return;
      }
      if (other.TestId.Length != 0) {
        TestId = other.TestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TestDTO : pb::IMessage<TestDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestDTO> _parser = new pb::MessageParser<TestDTO>(() => new TestDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestDTO(TestDTO other) : this() {
      testType_ = other.testType_;
      testAgeCategory_ = other.testAgeCategory_;
      noCompetitors_ = other.noCompetitors_;
      testId_ = other.testId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestDTO Clone() {
      return new TestDTO(this);
    }

    /// <summary>Field number for the "testType" field.</summary>
    public const int TestTypeFieldNumber = 1;
    private string testType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestType {
      get { return testType_; }
      set {
        testType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testAgeCategory" field.</summary>
    public const int TestAgeCategoryFieldNumber = 2;
    private string testAgeCategory_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestAgeCategory {
      get { return testAgeCategory_; }
      set {
        testAgeCategory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "noCompetitors" field.</summary>
    public const int NoCompetitorsFieldNumber = 3;
    private string noCompetitors_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NoCompetitors {
      get { return noCompetitors_; }
      set {
        noCompetitors_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testId" field.</summary>
    public const int TestIdFieldNumber = 4;
    private string testId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestId {
      get { return testId_; }
      set {
        testId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TestType != other.TestType) return false;
      if (TestAgeCategory != other.TestAgeCategory) return false;
      if (NoCompetitors != other.NoCompetitors) return false;
      if (TestId != other.TestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TestType.Length != 0) hash ^= TestType.GetHashCode();
      if (TestAgeCategory.Length != 0) hash ^= TestAgeCategory.GetHashCode();
      if (NoCompetitors.Length != 0) hash ^= NoCompetitors.GetHashCode();
      if (TestId.Length != 0) hash ^= TestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TestType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestType);
      }
      if (TestAgeCategory.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TestAgeCategory);
      }
      if (NoCompetitors.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NoCompetitors);
      }
      if (TestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TestType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestType);
      }
      if (TestAgeCategory.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TestAgeCategory);
      }
      if (NoCompetitors.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NoCompetitors);
      }
      if (TestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(TestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TestType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestType);
      }
      if (TestAgeCategory.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestAgeCategory);
      }
      if (NoCompetitors.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NoCompetitors);
      }
      if (TestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestDTO other) {
      if (other == null) {
        return;
      }
      if (other.TestType.Length != 0) {
        TestType = other.TestType;
      }
      if (other.TestAgeCategory.Length != 0) {
        TestAgeCategory = other.TestAgeCategory;
      }
      if (other.NoCompetitors.Length != 0) {
        NoCompetitors = other.NoCompetitors;
      }
      if (other.TestId.Length != 0) {
        TestId = other.TestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TestType = input.ReadString();
            break;
          }
          case 18: {
            TestAgeCategory = input.ReadString();
            break;
          }
          case 26: {
            NoCompetitors = input.ReadString();
            break;
          }
          case 34: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TestType = input.ReadString();
            break;
          }
          case 18: {
            TestAgeCategory = input.ReadString();
            break;
          }
          case 26: {
            NoCompetitors = input.ReadString();
            break;
          }
          case 34: {
            TestId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TestParticipantRelation : pb::IMessage<TestParticipantRelation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestParticipantRelation> _parser = new pb::MessageParser<TestParticipantRelation>(() => new TestParticipantRelation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestParticipantRelation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestParticipantRelation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestParticipantRelation(TestParticipantRelation other) : this() {
      testId_ = other.testId_;
      participantId_ = other.participantId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestParticipantRelation Clone() {
      return new TestParticipantRelation(this);
    }

    /// <summary>Field number for the "testId" field.</summary>
    public const int TestIdFieldNumber = 1;
    private string testId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestId {
      get { return testId_; }
      set {
        testId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participantId" field.</summary>
    public const int ParticipantIdFieldNumber = 2;
    private string participantId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParticipantId {
      get { return participantId_; }
      set {
        participantId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestParticipantRelation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestParticipantRelation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TestId != other.TestId) return false;
      if (ParticipantId != other.ParticipantId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TestId.Length != 0) hash ^= TestId.GetHashCode();
      if (ParticipantId.Length != 0) hash ^= ParticipantId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestId);
      }
      if (ParticipantId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TestId);
      }
      if (ParticipantId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParticipantId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestId);
      }
      if (ParticipantId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParticipantId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestParticipantRelation other) {
      if (other == null) {
        return;
      }
      if (other.TestId.Length != 0) {
        TestId = other.TestId;
      }
      if (other.ParticipantId.Length != 0) {
        ParticipantId = other.ParticipantId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TestId = input.ReadString();
            break;
          }
          case 18: {
            ParticipantId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TestId = input.ReadString();
            break;
          }
          case 18: {
            ParticipantId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CompetitionRequest : pb::IMessage<CompetitionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CompetitionRequest> _parser = new pb::MessageParser<CompetitionRequest>(() => new CompetitionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CompetitionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionRequest(CompetitionRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Empty:
          Empty = other.Empty;
          break;
        case PayloadOneofCase.User:
          User = other.User.Clone();
          break;
        case PayloadOneofCase.Participant:
          Participant = other.Participant.Clone();
          break;
        case PayloadOneofCase.TestDTO:
          TestDTO = other.TestDTO.Clone();
          break;
        case PayloadOneofCase.TestParticipantRelation:
          TestParticipantRelation = other.TestParticipantRelation.Clone();
          break;
        case PayloadOneofCase.Test:
          Test = other.Test.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionRequest Clone() {
      return new CompetitionRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Chat.Protocol.CompetitionRequest.Types.Type type_ = global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.CompetitionRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "empty" field.</summary>
    public const int EmptyFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Empty {
      get { return payloadCase_ == PayloadOneofCase.Empty ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Empty;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.User User {
      get { return payloadCase_ == PayloadOneofCase.User ? (global::Chat.Protocol.User) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.Participant Participant {
      get { return payloadCase_ == PayloadOneofCase.Participant ? (global::Chat.Protocol.Participant) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participant;
      }
    }

    /// <summary>Field number for the "testDTO" field.</summary>
    public const int TestDTOFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.TestDTO TestDTO {
      get { return payloadCase_ == PayloadOneofCase.TestDTO ? (global::Chat.Protocol.TestDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TestDTO;
      }
    }

    /// <summary>Field number for the "testParticipantRelation" field.</summary>
    public const int TestParticipantRelationFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.TestParticipantRelation TestParticipantRelation {
      get { return payloadCase_ == PayloadOneofCase.TestParticipantRelation ? (global::Chat.Protocol.TestParticipantRelation) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TestParticipantRelation;
      }
    }

    /// <summary>Field number for the "test" field.</summary>
    public const int TestFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.Test Test {
      get { return payloadCase_ == PayloadOneofCase.Test ? (global::Chat.Protocol.Test) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Test;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Empty = 2,
      User = 3,
      Participant = 4,
      TestDTO = 5,
      TestParticipantRelation = 6,
      Test = 7,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CompetitionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CompetitionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Empty != other.Empty) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(TestDTO, other.TestDTO)) return false;
      if (!object.Equals(TestParticipantRelation, other.TestParticipantRelation)) return false;
      if (!object.Equals(Test, other.Test)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Empty) hash ^= Empty.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Participant) hash ^= Participant.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TestDTO) hash ^= TestDTO.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) hash ^= TestParticipantRelation.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Test) hash ^= Test.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Empty) {
        output.WriteRawTag(18);
        output.WriteString(Empty);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(34);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.TestDTO) {
        output.WriteRawTag(42);
        output.WriteMessage(TestDTO);
      }
      if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) {
        output.WriteRawTag(50);
        output.WriteMessage(TestParticipantRelation);
      }
      if (payloadCase_ == PayloadOneofCase.Test) {
        output.WriteRawTag(58);
        output.WriteMessage(Test);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Empty) {
        output.WriteRawTag(18);
        output.WriteString(Empty);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(34);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.TestDTO) {
        output.WriteRawTag(42);
        output.WriteMessage(TestDTO);
      }
      if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) {
        output.WriteRawTag(50);
        output.WriteMessage(TestParticipantRelation);
      }
      if (payloadCase_ == PayloadOneofCase.Test) {
        output.WriteRawTag(58);
        output.WriteMessage(Test);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Empty) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Empty);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.TestDTO) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestDTO);
      }
      if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestParticipantRelation);
      }
      if (payloadCase_ == PayloadOneofCase.Test) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Test);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CompetitionRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Chat.Protocol.CompetitionRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Empty:
          Empty = other.Empty;
          break;
        case PayloadOneofCase.User:
          if (User == null) {
            User = new global::Chat.Protocol.User();
          }
          User.MergeFrom(other.User);
          break;
        case PayloadOneofCase.Participant:
          if (Participant == null) {
            Participant = new global::Chat.Protocol.Participant();
          }
          Participant.MergeFrom(other.Participant);
          break;
        case PayloadOneofCase.TestDTO:
          if (TestDTO == null) {
            TestDTO = new global::Chat.Protocol.TestDTO();
          }
          TestDTO.MergeFrom(other.TestDTO);
          break;
        case PayloadOneofCase.TestParticipantRelation:
          if (TestParticipantRelation == null) {
            TestParticipantRelation = new global::Chat.Protocol.TestParticipantRelation();
          }
          TestParticipantRelation.MergeFrom(other.TestParticipantRelation);
          break;
        case PayloadOneofCase.Test:
          if (Test == null) {
            Test = new global::Chat.Protocol.Test();
          }
          Test.MergeFrom(other.Test);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.CompetitionRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Empty = input.ReadString();
            break;
          }
          case 26: {
            global::Chat.Protocol.User subBuilder = new global::Chat.Protocol.User();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Protocol.Participant subBuilder = new global::Chat.Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Protocol.TestDTO subBuilder = new global::Chat.Protocol.TestDTO();
            if (payloadCase_ == PayloadOneofCase.TestDTO) {
              subBuilder.MergeFrom(TestDTO);
            }
            input.ReadMessage(subBuilder);
            TestDTO = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Protocol.TestParticipantRelation subBuilder = new global::Chat.Protocol.TestParticipantRelation();
            if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) {
              subBuilder.MergeFrom(TestParticipantRelation);
            }
            input.ReadMessage(subBuilder);
            TestParticipantRelation = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Protocol.Test subBuilder = new global::Chat.Protocol.Test();
            if (payloadCase_ == PayloadOneofCase.Test) {
              subBuilder.MergeFrom(Test);
            }
            input.ReadMessage(subBuilder);
            Test = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.CompetitionRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Empty = input.ReadString();
            break;
          }
          case 26: {
            global::Chat.Protocol.User subBuilder = new global::Chat.Protocol.User();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 34: {
            global::Chat.Protocol.Participant subBuilder = new global::Chat.Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 42: {
            global::Chat.Protocol.TestDTO subBuilder = new global::Chat.Protocol.TestDTO();
            if (payloadCase_ == PayloadOneofCase.TestDTO) {
              subBuilder.MergeFrom(TestDTO);
            }
            input.ReadMessage(subBuilder);
            TestDTO = subBuilder;
            break;
          }
          case 50: {
            global::Chat.Protocol.TestParticipantRelation subBuilder = new global::Chat.Protocol.TestParticipantRelation();
            if (payloadCase_ == PayloadOneofCase.TestParticipantRelation) {
              subBuilder.MergeFrom(TestParticipantRelation);
            }
            input.ReadMessage(subBuilder);
            TestParticipantRelation = subBuilder;
            break;
          }
          case 58: {
            global::Chat.Protocol.Test subBuilder = new global::Chat.Protocol.Test();
            if (payloadCase_ == PayloadOneofCase.Test) {
              subBuilder.MergeFrom(Test);
            }
            input.ReadMessage(subBuilder);
            Test = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CompetitionRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///    LOGIN, LOGOUT, GET_LOGGED_USERS, FIND_USER_BY_USERNAME, SAVE_PARTICIPANT, FIND_ALL_TEST_DTO,
      ///    SAVE_RELATION, FIND_PARTICIPANT_BY_USERNAME, FIND_ALL_PARTICIPANTS_FOR_TEST
      /// </summary>
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetLoggedUsers")] GetLoggedUsers = 3,
        [pbr::OriginalName("FindUserByUsername")] FindUserByUsername = 4,
        [pbr::OriginalName("SaveParticipant")] SaveParticipant = 5,
        [pbr::OriginalName("FindAllTestDto")] FindAllTestDto = 6,
        [pbr::OriginalName("SaveRelation")] SaveRelation = 7,
        [pbr::OriginalName("FindParticipantByUsername")] FindParticipantByUsername = 8,
        [pbr::OriginalName("FinAllParticipantsForTest")] FinAllParticipantsForTest = 9,
      }

    }
    #endregion

  }

  public sealed partial class CompetitionResponse : pb::IMessage<CompetitionResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CompetitionResponse> _parser = new pb::MessageParser<CompetitionResponse>(() => new CompetitionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CompetitionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.Protocol.CompetitionProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionResponse(CompetitionResponse other) : this() {
      type_ = other.type_;
      empty_ = other.empty_;
      error_ = other.error_;
      users_ = other.users_.Clone();
      user_ = other.user_ != null ? other.user_.Clone() : null;
      testDTOs_ = other.testDTOs_.Clone();
      participants_ = other.participants_.Clone();
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CompetitionResponse Clone() {
      return new CompetitionResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Chat.Protocol.CompetitionResponse.Types.Type type_ = global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.CompetitionResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "empty" field.</summary>
    public const int EmptyFieldNumber = 2;
    private string empty_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Empty {
      get { return empty_; }
      set {
        empty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "users" field.</summary>
    public const int UsersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Chat.Protocol.User> _repeated_users_codec
        = pb::FieldCodec.ForMessage(34, global::Chat.Protocol.User.Parser);
    private readonly pbc::RepeatedField<global::Chat.Protocol.User> users_ = new pbc::RepeatedField<global::Chat.Protocol.User>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Chat.Protocol.User> Users {
      get { return users_; }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 5;
    private global::Chat.Protocol.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "testDTOs" field.</summary>
    public const int TestDTOsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Chat.Protocol.TestDTO> _repeated_testDTOs_codec
        = pb::FieldCodec.ForMessage(50, global::Chat.Protocol.TestDTO.Parser);
    private readonly pbc::RepeatedField<global::Chat.Protocol.TestDTO> testDTOs_ = new pbc::RepeatedField<global::Chat.Protocol.TestDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Chat.Protocol.TestDTO> TestDTOs {
      get { return testDTOs_; }
    }

    /// <summary>Field number for the "participants" field.</summary>
    public const int ParticipantsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Chat.Protocol.Participant> _repeated_participants_codec
        = pb::FieldCodec.ForMessage(58, global::Chat.Protocol.Participant.Parser);
    private readonly pbc::RepeatedField<global::Chat.Protocol.Participant> participants_ = new pbc::RepeatedField<global::Chat.Protocol.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Chat.Protocol.Participant> Participants {
      get { return participants_; }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 8;
    private global::Chat.Protocol.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.Protocol.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CompetitionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CompetitionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Empty != other.Empty) return false;
      if (Error != other.Error) return false;
      if(!users_.Equals(other.users_)) return false;
      if (!object.Equals(User, other.User)) return false;
      if(!testDTOs_.Equals(other.testDTOs_)) return false;
      if(!participants_.Equals(other.participants_)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Empty.Length != 0) hash ^= Empty.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= users_.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      hash ^= testDTOs_.GetHashCode();
      hash ^= participants_.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Empty.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Empty);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Error);
      }
      users_.WriteTo(output, _repeated_users_codec);
      if (user_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(User);
      }
      testDTOs_.WriteTo(output, _repeated_testDTOs_codec);
      participants_.WriteTo(output, _repeated_participants_codec);
      if (participant_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Empty.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Empty);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Error);
      }
      users_.WriteTo(ref output, _repeated_users_codec);
      if (user_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(User);
      }
      testDTOs_.WriteTo(ref output, _repeated_testDTOs_codec);
      participants_.WriteTo(ref output, _repeated_participants_codec);
      if (participant_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Empty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Empty);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += users_.CalculateSize(_repeated_users_codec);
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      size += testDTOs_.CalculateSize(_repeated_testDTOs_codec);
      size += participants_.CalculateSize(_repeated_participants_codec);
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CompetitionResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Chat.Protocol.CompetitionResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Empty.Length != 0) {
        Empty = other.Empty;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      users_.Add(other.users_);
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Chat.Protocol.User();
        }
        User.MergeFrom(other.User);
      }
      testDTOs_.Add(other.testDTOs_);
      participants_.Add(other.participants_);
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::Chat.Protocol.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.CompetitionResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Empty = input.ReadString();
            break;
          }
          case 26: {
            Error = input.ReadString();
            break;
          }
          case 34: {
            users_.AddEntriesFrom(input, _repeated_users_codec);
            break;
          }
          case 42: {
            if (user_ == null) {
              User = new global::Chat.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 50: {
            testDTOs_.AddEntriesFrom(input, _repeated_testDTOs_codec);
            break;
          }
          case 58: {
            participants_.AddEntriesFrom(input, _repeated_participants_codec);
            break;
          }
          case 66: {
            if (participant_ == null) {
              Participant = new global::Chat.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Chat.Protocol.CompetitionResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Empty = input.ReadString();
            break;
          }
          case 26: {
            Error = input.ReadString();
            break;
          }
          case 34: {
            users_.AddEntriesFrom(ref input, _repeated_users_codec);
            break;
          }
          case 42: {
            if (user_ == null) {
              User = new global::Chat.Protocol.User();
            }
            input.ReadMessage(User);
            break;
          }
          case 50: {
            testDTOs_.AddEntriesFrom(ref input, _repeated_testDTOs_codec);
            break;
          }
          case 58: {
            participants_.AddEntriesFrom(ref input, _repeated_participants_codec);
            break;
          }
          case 66: {
            if (participant_ == null) {
              Participant = new global::Chat.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CompetitionResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///    OK, ERROR, NEW_PARTICIPANT, USER_LOGGED_IN, USER_LOGGED_OUT, GET_LOGGED_USERS,
      ///    FIND_USER_BY_USERNAME, FIND_ALL_TEST_DTO, FIND_PARTICIPANT_BY_USERNAME,FIND_ALL_PARTICIPANTS_FOR_TEST
      /// </summary>
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("NewParticipant")] NewParticipant = 3,
        [pbr::OriginalName("UserLoggedIn")] UserLoggedIn = 4,
        [pbr::OriginalName("UserLoggedOut")] UserLoggedOut = 5,
        [pbr::OriginalName("GetLoggedUsers")] GetLoggedUsers = 6,
        [pbr::OriginalName("FindUserByUsername")] FindUserByUsername = 7,
        [pbr::OriginalName("FindAllTestDto")] FindAllTestDto = 8,
        [pbr::OriginalName("FindParticipantByUsername")] FindParticipantByUsername = 9,
        [pbr::OriginalName("FindAllParticipantsForTest")] FindAllParticipantsForTest = 10,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
