namespace networking
{
    public enum ResponseType
    {
        OK, ERROR, NEW_PARTICIPANT, USER_LOGGED_IN, USER_LOGGED_OUT, GET_LOGGED_USERS,
        FIND_USER_BY_USERNAME, FIND_ALL_TEST_DTO, FIND_PARTICIPANT_BY_USERNAME,FIND_ALL_PARTICIPANTS_FOR_TEST
    }
}