package competition.network.rpcprotocol;

public enum RequestType {
    LOGIN, LOGOUT, GET_LOGGED_USERS, FIND_USER_BY_USERNAME, SAVE_PARTICIPANT, FIND_ALL_TEST_DTO,
    SAVE_RELATION, FIND_PARTICIPANT_BY_USERNAME, FIND_ALL_PARTICIPANTS_FOR_TEST
}
